DROP DATABASE IF EXISTS checkout;

CREATE DATABASE checkout;

USE checkout;

DROP TABLE IF EXISTS users;

CREATE TABLE users (

  id INTEGER NOT NULL AUTO_INCREMENT,
  first_name MEDIUMTEXT,
  last_name MEDIUMTEXT,
  email MEDIUMTEXT,
  password MEDIUMTEXT,
  orderId MEDIUMTEXT,
  PRIMARY KEY (id)

);

DROP TABLE IF EXISTS cards;

CREATE TABLE cards (

  id INTEGER NOT NULL AUTO_INCREMENT,
  number MEDIUMTEXT,
  expiry_month MEDIUMTEXT,
  expiry_year MEDIUMTEXT,
  cvv MEDIUMTEXT,
  zipcode MEDIUMTEXT,
  user INTEGER,
  orderId MEDIUMTEXT,
  PRIMARY KEY (id)

);

DROP TABLE IF EXISTS orders;

CREATE TABLE orders (

  id INTEGER NOT NULL AUTO_INCREMENT,
  line_1 MEDIUMTEXT,
  line_2 MEDIUMTEXT,
  city MEDIUMTEXT,
  state MEDIUMTEXT,
  zipcode MEDIUMTEXT,
  phone MEDIUMTEXT,
  user INTEGER,
  orderId MEDIUMTEXT,
  completed BOOLEAN,
  PRIMARY KEY (id)

);
